<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Roshan" ignored="6" name="Command line test" tests="3" failures="1" timestamp="29 Dec 2022 13:40:38 GMT" time="16.568" errors="0">
  <testcase name="validateCreateAirline" time="6.296" classname="com.test.testcases.CreateAirlineTest">
    <failure type="java.lang.AssertionError" message="expected [201] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [404]
at com.test.testcases.CreateAirlineTest.validateCreateAirline(CreateAirlineTest.java:30)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateAirline -->
  <testcase name="validateStatusCode" time="0.248" classname="com.test.testcases.GetAirlinesTest"/>
  <testcase name="validateName" time="2.831" classname="com.test.testcases.GetAirlinesTest"/>
  <testcase name="@BeforeTest startMock" time="0.0" classname="com.test.testcases.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest startMock -->
  <testcase name="@BeforeTest startMock" time="0.0" classname="com.test.testcases.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest startMock -->
  <testcase name="@AfterSuite afterSuite" time="0.0" classname="com.test.testcases.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
  <testcase name="@AfterSuite afterSuite" time="0.0" classname="com.test.testcases.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
  <testcase name="@BeforeSuite init" time="0.0" classname="com.test.testcases.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite init -->
  <testcase name="@BeforeSuite init" time="0.0" classname="com.test.testcases.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite init -->
</testsuite> <!-- Command line test -->
